### ISSUE TITLE
Community Page Image is using the PaperMC one

### ISSUE THREAD

**Issue by olijeffers0n** [LeavesMC/Website#1]
<https://github.com/LeavesMC/Website/blob/main/assets/images/community.png> 

This appears to be using the PaperMC image rather than the LeavesMC one. GitHub must have accidentally taken their image instead. I would expect a picture of the LeavesMC team to appear

**Comment by LittleChest** [comment]
We are currently understaffed, so this might take some time, but if you're interested, welcome to join us.
