### ISSUE TITLE
License Violation

### ISSUE THREAD

**Issue by kashike** [LeavesMC/Website#9]
The code in this repository is a modified version of the code found in the [PaperMC/website](<https://github.com/PaperMC/website>) repository. As per the [license file](<https://github.com/PaperMC/website/blob/main/LICENSE>) found in the original repository, you are required to keep all original copyright notices.

**Comment by LittleChest** [comment]
We follow the same license
https://github.com/LeavesMC/Website/blob/main/LICENSE

**Comment by kashike** [comment]
You do follow the same license, but you have removed the original copyright attributions to PaperMC.

**Comment by LittleChest** [comment]
> You do follow the same license, but you have removed the original copyright attributions to PaperMC.

Sorry, I will deal with this soon.
